### ISSUE TITLE
Can't import latest Zabbix template

### ISSUE THREAD

**Issue by jsosic** [jasonmcintosh/rabbitmq-zabbix#33] opened 2016-01-14 23:55 UTC
Latest I can import is from #0f501d72fa3509103b5042a1d97f2c1ba94f7883.

Zabbix 2.2.10
PHP 5.6.16
PostgreSQL 9.4

```
Created: Item "RabbitMQ Server Sockets Used" on "Template App RabbitMQ v3".
Created: Item "RabbitMQ Server Version" on "Template App RabbitMQ v3".
mb_strlen() expects parameter 1 to be string, array given [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → DB::checkValueTypes() → zbx_strlen() → mb_strlen() in /usr/share/zabbix/include/func.inc.php:955]
pg_escape_string() expects parameter 1 to be string, array given [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → DB::checkValueTypes() → zbx_dbstr() → pg_escape_string() in /usr/share/zabbix/include/db.inc.php:1242]
Array to string conversion [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → implode() in /usr/share/zabbix/include/classes/db/DB.php:450]
pg_query(): Query failed: ERROR:  syntax error at or near ","
LINE 1: ...0','0','','0','','','','','0','','','','','',Array,'1','','r...
                                                             ^ [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → DBexecute() → pg_query() in /usr/share/zabbix/include/db.inc.php:509]
Error in query [INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('rabbitmq queues','7','','','360','0','','','0','0','','0','','','','','0','','','','','',Array,'1','','rabbitmq.discovery_queue','','10219','1','4','0',NULL,'35977')] [ERROR:  syntax error at or near ","
LINE 1: ...0','0','','0','','','','','0','','','','','',Array,'1','','r...
                                                             ^]
SQL statement execution has failed "INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('rabbitmq queues','7','','','360','0','','','0','0','','0','','','','','0','','','','','',Array,'1','','rabbitmq.discovery_queue','','10219','1','4','0',NULL,'35977')".
```

**Comment by jasonmcintosh** [comment] 2016-01-25 17:49
This MIGHT be a duplicate of #29 - sadly I've not spent much time lately on this template stuff to dig into it.

**Comment by sww314** [comment] 2016-02-04 21:25
The latest template imports ok in Zabbix 3.0 (beta).

**Comment by jasonmcintosh** [comment] 2016-10-27 19:52
Closing old issue - please reopen if the latest release still has the issues.

**Closed by jasonmcintosh** 2016-10-27 19:52 UTC
