### ISSUE TITLE
Issues with RabbitMQ Refresh Rabbit Queue Status

### ISSUE THREAD

**Issue by perf3ktion** [jasonmcintosh/rabbitmq-zabbix#50] opened 2016-08-19 02:43 UTC
Hey Jason,

We have previously used the older version of your scripts to monitor RabbiMQ Queues, and now we are trying to install it on a new machine with the latest version and are running into a few issues.

To start off with, here are some versions:

**[Zabbix Server]**
Zabbix Server: 3.0.4
OS: CentOS 7.2.1511

**[Zabbix Host]**
OS: CentOS 6.6 (Final)
Zabbix Agent: Zabbix Agent (daemon) v2.4.8 (revision 59539) (20 April 2016)
Zabbix Sender: Zabbix Sender v2.4.8 (revision 59539) (20 April 2016)
RabbitMQ: 3.3.5

The Refresh Rabbit Queue Status is returning code 2, and i am at a loss as to why. If i run the command directly from the agent i get a response code of 2, as well as executing the script also returning the code 2:

```
[user@hostname rabbitmq]$ sudo zabbix_agentd -t rabbitmq[queues]
rabbitmq[queues]                              [t|2]
```

```
[user@ hostname rabbitmq]$ sudo ./rabbitmq-status.sh queues
2
```

Both list_rabbit_queues.sh and rabbitmq-status.sh list_queues are returning the list of all the queues.
Zabbix is able to receive queues data and message rates. When viewing the logs however it looks like zabbix-sender is failing to send the data to the zabbix server:

```
[user@ hostname zabbix]$ tail -f rabbitmq_zabbix.log
2016-08-19 12:01:41,709 INFO: Found return code of 2
2016-08-19 12:01:41,710 WARNING: info from server: "processed: 0; failed: 78; total: 78; seconds spent: 0.000546"
sent: 78; skipped: 0; total: 78
```

When i switch the logging level to debug i can see that it is getting all the right data, but it is just not making it there:

```
2016-08-19 11:58:47,447 WARNING:
2016-08-19 11:58:47,485 DEBUG: Started trying to process data
2016-08-19 11:58:47,486 DEBUG: Issue a rabbit API call to get data on queues
2016-08-19 11:58:47,508 DEBUG: Filtering out by [{u'durable': True}]
2016-08-19 11:58:47,508 DEBUG: Filtering out by [{u'durable': True}]
2016-08-19 11:58:47,510 DEBUG: SENDER_DATA: - "rabbitmq.queues[/,queue_memory,queue_name]" 23608
2016-08-19 11:58:47,510 DEBUG: SENDER_DATA: - "rabbitmq.queues[/,queue_messages, queue_name]" 0
2016-08-19 11:58:47,512 DEBUG: SENDER_DATA: - "rabbitmq.queues[/,queue_messages_unacknowledged, queue_name]" 0
2016-08-19 11:58:47,513 DEBUG: SENDER_DATA: - "rabbitmq.queues[/,queue_consumers, queue_name]" 10
2016-08-19 11:58:47,513 DEBUG: SENDER_DATA: - "rabbitmq.queues[/,queue_message_stats_deliver_get, queue_name]" 2589422
2016-08-19 11:58:47,513 DEBUG: SENDER_DATA: - "rabbitmq.queues[/,queue_message_stats_publish, queue_name]" 1943898
***** Omitted *****
2016-08-19 11:58:47,925 DEBUG: Finished sending data
2016-08-19 11:58:47,925 INFO: Found return code of 2
2016-08-19 11:58:47,925 WARNING: info from server: "processed: 0; failed: 78; total: 78; seconds spent: 0.000545"
sent: 78; skipped: 0; total: 78
```

There may be something we have missed here, and if you need any further information please let me know. I would really appreciate some guidance when you have a spare moment!

Regards,

Leigh

**Comment by plutoid** [comment] 2016-08-22 01:13
hi Leigh,

I　have same issue like yours, I　subscribed it in issues/47 too, since I'm not familiar discovery rules in zabbix, I still cannot get the cause for the issue.

BRs,
Hua

**Comment by jasonmcintosh** [comment] 2016-08-22 03:00
Looks like the same issue as #47 - discovery on the server side has no queues to be processed.  I'd check your server's discovery queue item and see if an error has been thrown there.

**Comment by kurok** [comment] 2016-09-30 16:35
Hi
I have same issue on the server,
after update zabbix to 3.2 I have in queues parameter "2" and incident triggered

Please explain which parameter in RabbitMQ pointed by  "queues" in Api.py

Thanks

**Comment by ebenezar-mccoy** [comment] 2016-10-07 07:39
Same me, discovery works just fine, statistics for queues as well.

the only problem i've got is this queue status "2"

 16957:20161007:093536.483 In zbx_popen() command:'/etc/zabbix/scripts/rabbitmq-status.sh queues  '
 16957:20161007:093536.808 EXECUTE_STR() command:'/etc/zabbix/scripts/rabbitmq-status.sh queues  ' len:1 cmd_result:'2'

/etc/zabbix/scripts/rabbitmq-status.sh queues
2

As kurok i also have 3.2 zabbix.

This issue occurred for me after deploying another version of application using several queues and bindings.

My question is: what status 2 means and how to determine with witch queue i have issue ?

**Comment by ebenezar-mccoy** [comment] 2016-10-10 10:43
After short time spent on debugging:

For me the problem was in exclusive queues (amq.gen-*), developer started to use those.

I have added filter FILTER='{"durable": true}' for durable queues in my rab.auth config.
And now status back to normal :)

**Comment by jasonmcintosh** [comment] 2016-10-14 19:19
Note with latest release I've changed the status code check to look for a COMPLETE failure, not just a partial failure (zabbix_sender code of 1 is complete failure, 2 is partial failure, e.g. filtered queues).  This should help - if no updates here in a few weeks I'll close this out :)

**Closed** 2016-10-27 19:57 UTC
